/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as MainLayoutImport } from './routes/_mainLayout'
import { Route as AuthLayoutImport } from './routes/_authLayout'
import { Route as MainLayoutexternalApiDetailsMalAnimeIdImport } from './routes/_mainLayout/(externalApiDetails)/mal/anime.$id'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
const MainLayoutDashboardLazyImport = createFileRoute(
  '/_mainLayout/dashboard',
)()
const AuthLayoutSignupLazyImport = createFileRoute('/_authLayout/signup')()
const AuthLayoutLoginLazyImport = createFileRoute('/_authLayout/login')()
const MainLayoutTrackrCreateLazyImport = createFileRoute(
  '/_mainLayout/trackr/create',
)()

// Create/Update Routes

const MainLayoutRoute = MainLayoutImport.update({
  id: '/_mainLayout',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const MainLayoutDashboardLazyRoute = MainLayoutDashboardLazyImport.update({
  path: '/dashboard',
  getParentRoute: () => MainLayoutRoute,
} as any).lazy(() =>
  import('./routes/_mainLayout/dashboard.lazy').then((d) => d.Route),
)

const AuthLayoutSignupLazyRoute = AuthLayoutSignupLazyImport.update({
  path: '/signup',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./routes/_authLayout/signup.lazy').then((d) => d.Route),
)

const AuthLayoutLoginLazyRoute = AuthLayoutLoginLazyImport.update({
  path: '/login',
  getParentRoute: () => AuthLayoutRoute,
} as any).lazy(() =>
  import('./routes/_authLayout/login.lazy').then((d) => d.Route),
)

const MainLayoutTrackrCreateLazyRoute = MainLayoutTrackrCreateLazyImport.update(
  {
    path: '/trackr/create',
    getParentRoute: () => MainLayoutRoute,
  } as any,
).lazy(() =>
  import('./routes/_mainLayout/trackr/create.lazy').then((d) => d.Route),
)

const MainLayoutexternalApiDetailsMalAnimeIdRoute =
  MainLayoutexternalApiDetailsMalAnimeIdImport.update({
    path: '/mal/anime/$id',
    getParentRoute: () => MainLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_mainLayout': {
      id: '/_mainLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_authLayout/login': {
      id: '/_authLayout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLayoutLoginLazyImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_authLayout/signup': {
      id: '/_authLayout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthLayoutSignupLazyImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_mainLayout/dashboard': {
      id: '/_mainLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof MainLayoutDashboardLazyImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/trackr/create': {
      id: '/_mainLayout/trackr/create'
      path: '/trackr/create'
      fullPath: '/trackr/create'
      preLoaderRoute: typeof MainLayoutTrackrCreateLazyImport
      parentRoute: typeof MainLayoutImport
    }
    '/_mainLayout/(externalApiDetails)/mal/anime/$id': {
      id: '/_mainLayout/mal/anime/$id'
      path: '/mal/anime/$id'
      fullPath: '/mal/anime/$id'
      preLoaderRoute: typeof MainLayoutexternalApiDetailsMalAnimeIdImport
      parentRoute: typeof MainLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  AuthLayoutRoute: AuthLayoutRoute.addChildren({
    AuthLayoutLoginLazyRoute,
    AuthLayoutSignupLazyRoute,
  }),
  MainLayoutRoute: MainLayoutRoute.addChildren({
    MainLayoutDashboardLazyRoute,
    MainLayoutTrackrCreateLazyRoute,
    MainLayoutexternalApiDetailsMalAnimeIdRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authLayout",
        "/_mainLayout"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/_authLayout": {
      "filePath": "_authLayout.tsx",
      "children": [
        "/_authLayout/login",
        "/_authLayout/signup"
      ]
    },
    "/_mainLayout": {
      "filePath": "_mainLayout.tsx",
      "children": [
        "/_mainLayout/dashboard",
        "/_mainLayout/trackr/create",
        "/_mainLayout/mal/anime/$id"
      ]
    },
    "/_authLayout/login": {
      "filePath": "_authLayout/login.lazy.tsx",
      "parent": "/_authLayout"
    },
    "/_authLayout/signup": {
      "filePath": "_authLayout/signup.lazy.tsx",
      "parent": "/_authLayout"
    },
    "/_mainLayout/dashboard": {
      "filePath": "_mainLayout/dashboard.lazy.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/trackr/create": {
      "filePath": "_mainLayout/trackr/create.lazy.tsx",
      "parent": "/_mainLayout"
    },
    "/_mainLayout/mal/anime/$id": {
      "filePath": "_mainLayout/(externalApiDetails)/mal/anime.$id.tsx",
      "parent": "/_mainLayout"
    }
  }
}
ROUTE_MANIFEST_END */
